# See NOTE comments for places to modify.
services:
  tts:
    image: moshi-server:latest
    restart: unless-stopped
    command: ["worker", "--config", "configs/tts.toml"]
    build:
      context: services/moshi-server
      dockerfile: public.Dockerfile
      args:
        FORCE_FLOAT_16: "false"
    environment:
      - HUGGING_FACE_HUB_TOKEN=$HUGGING_FACE_HUB_TOKEN
      - CUDA_COMPUTE_CAP=120
      - FORCE_FLOAT_16=${TTS_FORCE_FLOAT16}
    volumes:
      - ./volumes/cargo-registry-tts:/root/.cargo/registry
      - ./volumes/tts-target:/app/target
      - ./volumes/uv-cache:/root/.cache/uv
      - /tmp/models/:/models
      - ./volumes/tts-logs:/logs
    networks:
      - ansible
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['${TTS_GPU_DEVICE:-0}']
              capabilities: [gpu]

  stt:
    image: moshi-server:latest
    restart: unless-stopped
    command: ["worker", "--config", "configs/stt.toml"]
    build:
      context: services/moshi-server
      dockerfile: public.Dockerfile
      args:
        FORCE_FLOAT_16: "false"
    environment:
      - HUGGING_FACE_HUB_TOKEN=$HUGGING_FACE_HUB_TOKEN
      - CUDA_COMPUTE_CAP=120
      - FORCE_FLOAT_16=${STT_FORCE_FLOAT16}
    volumes:
      - ./volumes/cargo-registry-stt:/root/.cargo/registry
      - ./volumes/stt-target:/app/target
      - ./volumes/uv-cache:/root/.cache/uv
      - /tmp/models/:/models
      - ./volumes/stt-logs:/logs
    networks:
      - ansible
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['${STT_GPU_DEVICE:-0}']
              capabilities: [gpu]
networks:
  ansible:
    external: true
    name: ansible
